extends:
  - requarks
  - plugin:vue/strongly-recommended
  - plugin:cypress/recommended
env:
  node: true
  jest: true
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2017
  allowImportExportEverywhere: true
globals:
  document: false
  navigator: false
  window: false
